# general
run_name: 'test'

# code parameters
code_length: 87
info_length: 13
crc_length: 16 # only supports 16 bits in this setup
clipping_val: 20 # initialization absolute LLR value
n_states: 64

# train hyperparameters
num_of_minibatches: 100
train_minibatch_size: 100 # should be big enough
train_SNR_start: -2
train_SNR_end: 0
train_num_SNR: 3 # how many equally spaced values, including edges
training_words_factor: 200
lr: 0.001 # learning rate
load_from_checkpoint: False # loads last checkpoint, if exists in the run_name folder
validation_minibatches_frequency: 10 # validate every number of minibatches
save_checkpoint_minibatches: 20 # save checkpoint every

# validation hyperparameters
val_minibatch_size: 3000 # the more the merrier
val_SNR_start: -2
val_SNR_end: 2
val_num_SNR: 5 # how many equally spaced values
thresh_errors: 250 # monte-carlo error threshold per point

# seed
noise_seed: 345002
word_seed: 786002

# CVA/WCVA parameters
replications: 3

# WCVAE
decoders_in_ensemble: 8

# LGVA
list_size: 8
